# SPDX-License-Identifier: LicenseRef-FolderTally-Noncommercial-1.0
# Copyright (C) 2026 PradaFit

"""Add reading-order structure to PDF text generated by FolderTally."""
import os
from pathlib import Path


def tag_report(path, page_counts, cancelled=None):
    from pypdf import PdfReader, PdfWriter
    from pypdf.generic import (ArrayObject, BooleanObject, DictionaryObject, DecodedStreamObject,
                              NameObject, NumberObject, TextStringObject)
    from FolderTally import ScanCancelled

    def check():
        if cancelled and cancelled(): raise ScanCancelled()

    def dictionary(**values):
        return DictionaryObject({NameObject("/" + key): value for key, value in values.items()})

    check()
    staged = Path(path).with_suffix(".tagged.pdf")
    # The only input is our own freshly generated report, never an arbitrary PDF.
    with Path(path).open("rb") as original:
        writer = PdfWriter(clone_from=PdfReader(original))
        writer.pdf_header = b"%PDF-1.7"
        metadata = DecodedStreamObject()
        metadata.set_data(b'''<?xpacket begin="\xef\xbb\xbf" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="" xmlns:pdfuaid="http://www.aiim.org/pdfua/ns/id/"
    xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:pdf="http://ns.adobe.com/pdf/1.3/" pdfuaid:part="1">
   <dc:title><rdf:Alt><rdf:li xml:lang="x-default">FolderTally | Folder inventory</rdf:li></rdf:Alt></dc:title>
   <dc:creator><rdf:Seq><rdf:li>FolderTally</rdf:li></rdf:Seq></dc:creator>
   <dc:language><rdf:Bag><rdf:li>en-US</rdf:li></rdf:Bag></dc:language>
   <xmp:CreatorTool>FolderTally</xmp:CreatorTool>
   <pdf:Producer>ReportLab and pypdf</pdf:Producer>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>''')
        metadata[NameObject("/Type")] = NameObject("/Metadata")
        metadata[NameObject("/Subtype")] = NameObject("/XML")
        writer.root_object[NameObject("/Metadata")] = writer._add_object(metadata)
        root = dictionary(Type=NameObject("/StructTreeRoot"))
        root_ref = writer._add_object(root)
        document = dictionary(Type=NameObject("/StructElem"), S=NameObject("/Document"), P=root_ref)
        document_ref = writer._add_object(document)
        children = ArrayObject()
        parents = ArrayObject()
        first = True
        for index, (page, count) in enumerate(zip(writer.pages, page_counts, strict=True)):
            check()
            page[NameObject("/StructParents")] = NumberObject(index)
            page[NameObject("/Tabs")] = NameObject("/S")
            elements = ArrayObject()
            for mcid in range(count):
                element = dictionary(Type=NameObject("/StructElem"), S=NameObject("/H1" if first else "/P"),
                                     P=document_ref, Pg=page.indirect_reference, K=NumberObject(mcid))
                first = False
                ref = writer._add_object(element)
                children.append(ref); elements.append(ref)
            parents.extend([NumberObject(index), elements])
        document[NameObject("/K")] = children
        root[NameObject("/K")] = ArrayObject([document_ref])
        root[NameObject("/ParentTree")] = writer._add_object(dictionary(Nums=parents))
        root[NameObject("/ParentTreeNextKey")] = NumberObject(len(page_counts))
        writer.root_object[NameObject("/StructTreeRoot")] = root_ref
        writer.root_object[NameObject("/MarkInfo")] = dictionary(Marked=BooleanObject(True))
        writer.root_object[NameObject("/Lang")] = TextStringObject("en-US")
        writer.root_object[NameObject("/ViewerPreferences")] = dictionary(DisplayDocTitle=BooleanObject(True))
        check()
        with staged.open("wb") as output:
            writer.write(output)
        writer.close()
    check()
    os.replace(staged, path)
